// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOh0WW842f109CgTdjQ_ddFycv_9KSqU0',
    appId: '1:400738570869:web:518f7f2b51fbdc4ebd5e3c',
    messagingSenderId: '400738570869',
    projectId: 'campus-carpool-abb2a',
    authDomain: 'campus-carpool-abb2a.firebaseapp.com',
    databaseURL: 'https://campus-carpool-abb2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-carpool-abb2a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfKoi5I-3sLVES9tVt9Y6RMZW0KcmmvuY',
    appId: '1:400738570869:android:b8c5bf7e094d6da4bd5e3c',
    messagingSenderId: '400738570869',
    projectId: 'campus-carpool-abb2a',
    databaseURL: 'https://campus-carpool-abb2a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'campus-carpool-abb2a.firebasestorage.app',
  );

}